server:
  servlet:
    context-path: /yummer
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
  datasource:
    url: 'jdbc:h2:mem:testdb'
    driverClassName: org.h2.Driver
    username: yummer
    password: yummer
  h2:
    console:
      enabled: true
      path: /h2-console  # http://localhost:8080/yummer/h2-console
